# Generated by Django 3.0.4 on 2020-03-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('big_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.FoodType')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAdditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('big_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Plate')),
            ],
        ),
    ]
