# Generated by Django 3.0.4 on 2020-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200329_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
